version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    #image: iricshkin/foodgram_backend:latest
    #restart: always
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - static_value:/app/backend_static/:rw
      - media_value:/app/backend_media/:rw
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    # image: iricshkin/foodgram_frontend:latest
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/usr/share/nginx/html/backend_static/:ro
      - media_value:/usr/share/nginx/html/backend_media:ro
      # - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      # - static_value:/var/html/backend_static/:ro
      # - media_value:/var/html/backend_media/:ro
    depends_on:
      - backend

volumes:
  postgres_data:
  static_value:
  media_value:
