# Generated by Django 2.2.19 on 2022-07-13 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220712_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, help_text='Введите логин', max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-+\\\\z]', 'Неверные символы')], verbose_name='Логин'),
        ),
    ]
